// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Availability struct {
	ID       int       `json:"id"`
	StayDate time.Time `json:"stayDate"`
	AvlCount int       `json:"avlCount"`
	Room     []*Room   `json:"room,omitempty"`
}

type Category struct {
	ID          int     `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Rooms       []*Room `json:"rooms,omitempty"`
}

type FoodPlan struct {
	ID       int       `json:"id"`
	Name     string    `json:"name"`
	Tariff   *int      `json:"tariff,omitempty"`
	NonVeg   *bool     `json:"nonVeg,omitempty"`
	Homestay *Homestay `json:"homestay,omitempty"`
}

type Homestay struct {
	ID       int       `json:"id"`
	Name     *string   `json:"name,omitempty"`
	Address  *string   `json:"address,omitempty"`
	Location *Location `json:"location,omitempty"`
	Rooms    []*Room   `json:"rooms,omitempty"`
}

type Location struct {
	ID          int         `json:"id"`
	Name        *string     `json:"name,omitempty"`
	Lat         *float64    `json:"lat,omitempty"`
	Long        *float64    `json:"long,omitempty"`
	State       *string     `json:"state,omitempty"`
	Altitude    *int        `json:"altitude,omitempty"`
	Description *string     `json:"description,omitempty"`
	CoverURL    *string     `json:"coverUrl,omitempty"`
	Homestays   []*Homestay `json:"homestays,omitempty"`
}

type Mutation struct {
}

type NewHomestay struct {
	Name         string `json:"name"`
	Address      string `json:"address"`
	LocationName string `json:"locationName"`
}

type NewLocation struct {
	Name        string  `json:"name"`
	Lat         float64 `json:"lat"`
	Long        float64 `json:"long"`
	State       string  `json:"state"`
	Altitude    int     `json:"altitude"`
	Description *string `json:"description,omitempty"`
	CoverURL    string  `json:"coverUrl"`
}

type NewRoom struct {
	Name                string `json:"name"`
	Occupancy           int    `json:"occupancy"`
	RoomCount           *int   `json:"roomCount,omitempty"`
	ToiletAttached      *bool  `json:"toiletAttached,omitempty"`
	BalconyAttached     *bool  `json:"balconyAttached,omitempty"`
	KitchenAttached     *bool  `json:"kitchenAttached,omitempty"`
	AirConditioned      *bool  `json:"airConditioned,omitempty"`
	HouseRecommendation *bool  `json:"houseRecommendation,omitempty"`
	IsDorm              *bool  `json:"isDorm,omitempty"`
	CategoryID          string `json:"categoryId"`
	HomestayID          string `json:"homestayId"`
}

type Query struct {
}

type Room struct {
	ID                  int       `json:"id"`
	Name                string    `json:"name"`
	RoomCount           *int      `json:"roomCount,omitempty"`
	Occupancy           *int      `json:"occupancy,omitempty"`
	ToiletAttached      *bool     `json:"toiletAttached,omitempty"`
	BalconyAttached     *bool     `json:"balconyAttached,omitempty"`
	KitchenAttached     *bool     `json:"kitchenAttached,omitempty"`
	AirConditioned      *bool     `json:"airConditioned,omitempty"`
	HouseRecommendation *bool     `json:"houseRecommendation,omitempty"`
	IsDorm              *bool     `json:"isDorm,omitempty"`
	Category            *Category `json:"category,omitempty"`
	FoodPlan            *FoodPlan `json:"foodPlan,omitempty"`
	Homestay            *Homestay `json:"homestay,omitempty"`
}
