// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Homestay struct {
	ID       int       `json:"id"`
	Name     *string   `json:"name,omitempty"`
	Address  *string   `json:"address,omitempty"`
	Location *Location `json:"location,omitempty"`
	Rooms    []*Room   `json:"rooms,omitempty"`
}

type Location struct {
	ID          int         `json:"id"`
	Name        *string     `json:"name,omitempty"`
	Lat         *float64    `json:"lat,omitempty"`
	Long        *float64    `json:"long,omitempty"`
	State       *string     `json:"state,omitempty"`
	Altitude    *int        `json:"altitude,omitempty"`
	Description *string     `json:"description,omitempty"`
	CoverURL    *string     `json:"coverUrl,omitempty"`
	Homestays   []*Homestay `json:"homestays,omitempty"`
}

type Mutation struct {
}

type NewHomestay struct {
	Name       string `json:"name"`
	Address    string `json:"address"`
	LocationID int    `json:"locationId"`
}

type NewLocation struct {
	Name        string  `json:"name"`
	Lat         float64 `json:"lat"`
	Long        float64 `json:"long"`
	State       string  `json:"state"`
	Altitude    int     `json:"altitude"`
	Description *string `json:"description,omitempty"`
	CoverURL    string  `json:"coverUrl"`
}

type NewRoom struct {
	Name            string `json:"name"`
	Category        string `json:"category"`
	BaseOccupancy   int    `json:"baseOccupancy"`
	ExtraOccupancy  *int   `json:"extraOccupancy,omitempty"`
	ToiletAttached  *bool  `json:"toiletAttached,omitempty"`
	BalconyAttached *bool  `json:"balconyAttached,omitempty"`
	KitchenAttached *bool  `json:"kitchenAttached,omitempty"`
	AirConditioned  *bool  `json:"airConditioned,omitempty"`
	Recommended     *bool  `json:"recommended,omitempty"`
	IsDorm          *bool  `json:"isDorm,omitempty"`
	HomestayID      int    `json:"homestayId"`
}

type Query struct {
}

type Room struct {
	ID              int       `json:"id"`
	Name            string    `json:"name"`
	Category        string    `json:"category"`
	BaseOccupancy   *int      `json:"baseOccupancy,omitempty"`
	ExtraOccupancy  *int      `json:"extraOccupancy,omitempty"`
	ToiletAttached  *bool     `json:"toiletAttached,omitempty"`
	BalconyAttached *bool     `json:"balconyAttached,omitempty"`
	KitchenAttached *bool     `json:"kitchenAttached,omitempty"`
	AirConditioned  *bool     `json:"airConditioned,omitempty"`
	Recommended     *bool     `json:"recommended,omitempty"`
	IsDorm          *bool     `json:"isDorm,omitempty"`
	Homestay        *Homestay `json:"homestay,omitempty"`
}
